let nomeDoHeroi = "Lobo ALFA "
let  xp  = 120.0000

if( xp  <= 1.000){
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + "Ferro" )
}
else if( xp >= 1.001 &&  xp  <= 2.000){
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + "Bronze" )
}
else if( xp >= 2.001 &&  xp  <= 5.000){
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + "Prata" )
}
else if( xp  >= 5.001 &&  xp <= 7.000){
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + "Ouro" )
}
else if(  xp >= 7.001 &&  xp  <= 8.000){
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + "Platina" )
}
else if( xp  >= 8.001 &&  xp  <= 9.000){
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + "Ascendete" )
}
else if( xp  >= 9.001 &&  xp  <= 10.000){
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + " Imortal" )
}
else( xp >= 10.001);{
    console.log( "O Herói de nome " + nomeDoHeroi + "está no nivel de " + "Radiante" )
}
